"""
test_loewner.py -- validates rom_engine.loewner.LoewnerROM.

Checks (mirroring docs/loewner_modal_identification_roadmap.md Section 6):
  1. Non-intrusiveness as a CHECKED property, not just a design intent:
     LoewnerROM.fit()'s signature only accepts frequency/response
     arrays -- no M/C/K parameter exists for a caller to (mis)use.
  2. Synthetic mass-spring-damper sanity check: identified frequencies
     and damping ratios match a known closed-form ground truth.
  3. Real fea_engine fixture: response data generated by fea_engine's
     OWN solve_harmonic() (never a hand-built matrix), fed only as
     (omega, x) arrays into LoewnerROM.fit(), compared against the
     fixture's own eigh()-based modal solution.
  4. Mode-shape reconstruction (Eq. 28) recovers the true mode shapes
     (checked via MAC, rom_engine.metrics).
  5. Input-validation errors: coincident interpolation frequencies,
     mismatched array lengths, wrong reconstruct_mode_shapes() shape,
     and a wrong omega_beta are all rejected loudly rather than
     silently producing a meaningless answer.
"""
import inspect
import numpy as np
import pytest
from scipy.linalg import eigh

from rom_engine.loewner import LoewnerROM
from rom_engine.metrics import modal_assurance_criterion
import fea_fixtures as ff
import loewner_fixtures as lf


def _match_and_report(f_true, eta_true, f_id, eta_id, tol_f=0.01, label=""):
    """Match each true mode to its nearest identified frequency (within
    tol_f relative error) and return the matched (f_err, eta_err) pairs
    -- the same nearest-frequency matching convention already used by
    fem_rom_comparison.py, since a raw (unscreened) LoewnerROM fit can
    contain extra, non-physical eigenpairs interleaved with the genuine
    ones (screening.py, Phase 3, is what removes those automatically;
    this basic Phase 2 test just needs the genuine ones to be FINDABLE
    among the raw output)."""
    matched = []
    print(f"\n{label} -- {'mode':>4} {'f_true':>10} {'f_id':>10} {'f_err%':>8} "
          f"{'eta_true':>10} {'eta_id':>10}")
    for i in range(len(f_true)):
        j = np.argmin(np.abs(f_id - f_true[i]))
        f_err = abs(f_id[j] - f_true[i]) / f_true[i]
        print(f"{'':>{len(label)+3}} {i:>4} {f_true[i]:>10.3f} {f_id[j]:>10.3f} "
              f"{100*f_err:>8.3f} {eta_true[i]:>10.5f} {eta_id[j]:>10.5f}")
        assert f_err < tol_f, (
            f"{label}: true mode {i} (f={f_true[i]:.3f} Hz) has no identified "
            f"mode within {100*tol_f:.1f}% -- nearest is {f_id[j]:.3f} Hz "
            f"({100*f_err:.2f}% off)")
        matched.append((f_err, eta_id[j] - eta_true[i]))
    return matched


def test_fit_signature_never_accepts_system_matrices():
    """Structural, checked non-intrusiveness: fit()'s parameter list is
    exactly the frequency/response arrays the method needs -- no way to
    (even accidentally) pass K, M, or C through it."""
    params = set(inspect.signature(LoewnerROM.fit).parameters)
    assert params == {"omega_alpha", "omega_beta", "x_alpha", "x_beta"}, (
        f"LoewnerROM.fit() must only accept response-sample arrays, got params {params}")


def test_synthetic_mass_spring_identifies_known_modes():
    rng = np.random.default_rng(42)
    M, C, K, alpha, beta = lf.build_system(n=15, rng=rng)

    f_all, eta_all, _ = lf.ground_truth_modes(M, C, K, alpha, beta, 0, 1e6)
    fmin, fmax = 0.7 * f_all[0], 1.3 * f_all[5]
    f_true, eta_true, _ = lf.ground_truth_modes(M, C, K, alpha, beta, fmin, fmax)
    n_modes = len(f_true)

    ref_dof = 4
    F = rng.standard_normal(M.shape[0])
    n_pool = 60
    f_pool_hz = np.linspace(fmin, fmax, n_pool) * (1 + 1e-3 * rng.standard_normal(n_pool))
    omega_pool = 2 * np.pi * f_pool_hz
    x_pool = lf.frf(omega_pool, F, M, C, K)[ref_dof, :]

    n_interp = n_modes + 3   # deliberately oversized, per the paper's guidance
    idx = rng.choice(n_pool, size=2 * n_interp, replace=False)
    idx_a, idx_b = idx[:n_interp], idx[n_interp:]
    rom = LoewnerROM.fit(omega_pool[idx_a], omega_pool[idx_b], x_pool[idx_a], x_pool[idx_b])

    in_band = (rom.f >= fmin) & (rom.f <= fmax) & (rom.eta >= 0) & (rom.eta <= 1)
    f_id, eta_id = rom.f[in_band], rom.eta[in_band]
    print(f"raw in-band eigenpairs: {in_band.sum()} vs {n_modes} true modes")

    matched = _match_and_report(f_true, eta_true, f_id, eta_id, tol_f=0.01,
                                 label="synthetic")
    max_f_err = max(abs(e[0]) for e in matched)
    print(f"max frequency error across matched modes: {100*max_f_err:.3f}%")


def test_real_fea_engine_cantilever_identifies_known_modes():
    fx = ff.damped_cantilever_beam_system(n=20)
    free = fx["free_dofs"]
    Kff = fx["K"][np.ix_(free, free)]
    Mff = fx["M"][np.ix_(free, free)]
    Cff = fx["C"][np.ix_(free, free)]
    sysobj = fx["sys"]
    n_dof = fx["n_dof"]

    # NOTE: pick the target band from the UNDAMPED natural frequencies
    # (eigh(Kff, Mff)), not from ground_truth_modes() with fmin=0 --
    # stiffness-proportional Rayleigh damping overdamps (zeta > 1) this
    # model's higher modes, which get clipped to f=0 by
    # ground_truth_modes() and would sort to the very front of an
    # fmin=0 scan, corrupting the band. This is the exact pitfall
    # documented in fem_rom_comparison.py's run_case() -- avoided here
    # the same way: derive the band from undamped frequencies first.
    wn2, _ = eigh(Kff, Mff)
    wn = np.sqrt(np.abs(wn2))
    f_undamped = wn / (2 * np.pi)
    fmin, fmax = 0.7 * f_undamped[0], 1.3 * f_undamped[3]
    f_true, eta_true, _ = lf.ground_truth_modes(Mff, Cff, Kff, fx["alpha"], fx["beta"], fmin, fmax)
    n_modes = len(f_true)

    tip_dof = n_dof - 2
    F_full = np.zeros(n_dof)
    F_full[tip_dof] = 1000.0

    rng = np.random.default_rng(7)
    n_pool = 100
    f_pool_hz = np.linspace(fmin, fmax, n_pool) * (1 + 1e-3 * rng.standard_normal(n_pool))
    omega_pool = 2 * np.pi * f_pool_hz
    # fea_engine's OWN harmonic solver generates the "measured" data --
    # LoewnerROM.fit() below only ever sees the resulting complex
    # scalars at one reference dof, never Kff/Mff/Cff/F_full again.
    x_pool = np.array([sysobj.solve_harmonic(w, F_full)[tip_dof] for w in omega_pool])

    n_interp = n_modes + 3
    idx = rng.choice(n_pool, size=2 * n_interp, replace=False)
    idx_a, idx_b = idx[:n_interp], idx[n_interp:]
    rom = LoewnerROM.fit(omega_pool[idx_a], omega_pool[idx_b], x_pool[idx_a], x_pool[idx_b])

    in_band = (rom.f >= fmin) & (rom.f <= fmax) & (rom.eta >= 0) & (rom.eta <= 1)
    f_id, eta_id = rom.f[in_band], rom.eta[in_band]
    print(f"raw in-band eigenpairs: {in_band.sum()} vs {n_modes} true modes")

    _match_and_report(f_true, eta_true, f_id, eta_id, tol_f=0.02, label="fea_engine cantilever")


def test_reconstruct_mode_shapes_matches_true_shapes_via_mac():
    rng = np.random.default_rng(3)
    M, C, K, alpha, beta = lf.build_system(n=15, rng=rng)
    f_all, eta_all, Phi_all = lf.ground_truth_modes(M, C, K, alpha, beta, 0, 1e6)
    fmin, fmax = 0.7 * f_all[0], 1.3 * f_all[4]
    f_true, eta_true, Phi_true = lf.ground_truth_modes(M, C, K, alpha, beta, fmin, fmax)
    n_modes = len(f_true)

    ref_dof = 4
    F = rng.standard_normal(M.shape[0])
    n_pool = 60
    f_pool_hz = np.linspace(fmin, fmax, n_pool) * (1 + 1e-3 * rng.standard_normal(n_pool))
    omega_pool = 2 * np.pi * f_pool_hz
    x_pool_ref = lf.frf(omega_pool, F, M, C, K)[ref_dof, :]

    n_interp = n_modes + 3
    idx = rng.choice(n_pool, size=2 * n_interp, replace=False)
    idx_a, idx_b = idx[:n_interp], idx[n_interp:]
    rom = LoewnerROM.fit(omega_pool[idx_a], omega_pool[idx_b],
                          x_pool_ref[idx_a], x_pool_ref[idx_b])

    meas_dofs = list(range(M.shape[0]))   # full-field reconstruction
    X_beta_multi = lf.frf(omega_pool[idx_b], F, M, C, K)[meas_dofs, :]
    Phi_ident = rom.reconstruct_mode_shapes(X_beta_multi, omega_beta=omega_pool[idx_b])

    print(f"\n{'mode':>4} {'f_true':>10} {'MAC':>8}")
    for i in range(n_modes):
        j = np.argmin(np.abs(rom.f - f_true[i]))
        mac = modal_assurance_criterion(Phi_ident[:, j], Phi_true[:, i])
        print(f"{i:>4} {f_true[i]:>10.3f} {mac:>8.4f}")
        assert mac > 0.9, f"mode {i} (f={f_true[i]:.3f} Hz): MAC={mac:.4f} too low"


def test_fit_rejects_coincident_interpolation_frequencies():
    omega_alpha = np.array([10.0, 20.0, 30.0])
    omega_beta = np.array([15.0, 20.0, 35.0])   # shares 20.0 with omega_alpha
    x = np.array([1 + 1j, 2 + 2j, 3 + 3j])
    with pytest.raises(ValueError, match="(?i)disjoint"):
        LoewnerROM.fit(omega_alpha, omega_beta, x, x)


def test_fit_rejects_mismatched_lengths():
    with pytest.raises(ValueError):
        LoewnerROM.fit(np.array([1.0, 2.0]), np.array([3.0]),
                        np.array([1j, 1j]), np.array([1j]))


def test_reconstruct_mode_shapes_rejects_wrong_column_count():
    omega_alpha = np.array([10.0, 30.0])
    omega_beta = np.array([15.0, 35.0])
    rng = np.random.default_rng(0)
    x_alpha = rng.standard_normal(2) + 1j * rng.standard_normal(2)
    x_beta = rng.standard_normal(2) + 1j * rng.standard_normal(2)
    rom = LoewnerROM.fit(omega_alpha, omega_beta, x_alpha, x_beta)

    wrong_shape = np.zeros((3, 5), dtype=complex)   # should be (n_meas, 2)
    with pytest.raises(ValueError):
        rom.reconstruct_mode_shapes(wrong_shape)


def test_reconstruct_mode_shapes_rejects_wrong_omega_beta():
    omega_alpha = np.array([10.0, 30.0])
    omega_beta = np.array([15.0, 35.0])
    rng = np.random.default_rng(0)
    x_alpha = rng.standard_normal(2) + 1j * rng.standard_normal(2)
    x_beta = rng.standard_normal(2) + 1j * rng.standard_normal(2)
    rom = LoewnerROM.fit(omega_alpha, omega_beta, x_alpha, x_beta)

    right_shape = np.zeros((3, 2), dtype=complex)
    with pytest.raises(ValueError):
        rom.reconstruct_mode_shapes(right_shape, omega_beta=np.array([99.0, 100.0]))
